version: '3'

services:

  nodehello:
    environment:
      - NODE_ENV=development
    image: educative1/nodehello
    container_name: nodehello
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
      - "8080:9229"
